/**
 * pdf-report.js — SimuVerse academic-quality PDF export
 *
 * Requires jsPDF (window.jspdf) and jsPDF-AutoTable (doc.autoTable).
 * Both are loaded via CDN in dashboard.html.
 *
 * Call:  window.SimuVersePDF.generate(data)
 * where `data` is built by buildPdfPayload() in dashboard.js.
 */
(function (global) {
  "use strict";

  /* Structured PDF export only — this builds a clean report from saved data,
     not from a screenshot of the live dashboard. */

  /* ── Design tokens (RGB) ─────────────────────────────────────── */
  const C = {
    navy:    [15,  34,  56],
    blue:    [22,  103, 245],
    blue2:   [18,  85,  204],
    teal:    [31,  143, 131],
    red:     [214, 59,  59],
    amber:   [192, 124, 24],
    muted:   [100, 116, 139],
    muted2:  [63,  82,  104],
    line:    [218, 226, 238],
    bg:      [240, 244, 249],
    bgBlue:  [232, 241, 255],
    white:   [255, 255, 255],
    black:   [0,   0,   0],
  };

  /* ── Layout constants (mm, A4) ───────────────────────────────── */
  const W = 210, H = 297, M = 18, CW = W - M * 2;

  /* ── Colour helpers ──────────────────────────────────────────── */
  function fc(doc, rgb) { doc.setFillColor(rgb[0], rgb[1], rgb[2]); }
  function tc(doc, rgb) { doc.setTextColor(rgb[0], rgb[1], rgb[2]); }
  function dc(doc, rgb) { doc.setDrawColor(rgb[0], rgb[1], rgb[2]); }

  /* ── Typography helpers ──────────────────────────────────────── */
  function font(doc, size, weight, color) {
    doc.setFont("helvetica", weight === "bold" ? "bold" : "normal");
    doc.setFontSize(size);
    if (color) tc(doc, color);
  }

  /* ── Draw a horizontal rule ──────────────────────────────────── */
  function hRule(doc, y, color, width) {
    dc(doc, color || C.line);
    doc.setLineWidth(width || 0.3);
    doc.line(M, y, W - M, y);
  }

  /* ── Page header strip ───────────────────────────────────────── */
  function pageHeader(doc, title, pageLabel) {
    fc(doc, C.navy);
    doc.rect(0, 0, W, 14, "F");
    font(doc, 8, "bold", C.white);
    doc.text("SIMUVERSE RUN REPORT", M, 9);
    font(doc, 8, "normal", [180, 195, 215]);
    doc.text(title, M + 44, 9);
    font(doc, 7, "normal", [160, 178, 200]);
    doc.text(pageLabel, W - M, 9, { align: "right" });
  }

  /* ── Page footer ─────────────────────────────────────────────── */
  function pageFooter(doc, runId, pageNum, total) {
    dc(doc, C.line);
    doc.setLineWidth(0.3);
    doc.line(M, H - 13, W - M, H - 13);
    font(doc, 7, "normal", C.muted);
    doc.text(`Generated by SimuVerse - Run ID: ${pdfSafe(runId)}`, M, H - 8);
    const pageText = total != null ? `Page ${pageNum} of ${total}` : `Page ${pageNum}`;
    doc.text(pageText, W - M, H - 8, { align: "right" });
  }

  /* ── Eyebrow / section label ─────────────────────────────────── */
  function eyebrow(doc, y, text) {
    font(doc, 7.5, "bold", C.blue);
    doc.text(text.toUpperCase(), M, y);
    return y + 5;
  }

  /* ── Section heading ─────────────────────────────────────────── */
  function sectionHead(doc, y, text) {
    font(doc, 15, "bold", C.navy);
    doc.text(text, M, y);
    return y + 8;
  }

  /* ── Coloured metric chip ────────────────────────────────────── */
  function metricChip(doc, x, y, w, label, value, color, sub) {
    const h = sub ? 22 : 18;
    fc(doc, C.bg);
    doc.roundedRect(x, y, w, h, 3, 3, "F");
    dc(doc, color || C.blue);
    doc.setLineWidth(0.4);
    doc.roundedRect(x, y, w, h, 3, 3, "S");
    font(doc, 6.5, "bold", C.muted);
    doc.text(label.toUpperCase(), x + 6, y + 6);
    font(doc, 14, "bold", color || C.navy);
    doc.text(String(value), x + 6, y + 14);
    if (sub) {
      font(doc, 6, "normal", C.muted);
      doc.text(sub, x + 6, y + 20);
    }
  }

  /* ── Outcome badge ───────────────────────────────────────────── */
  function isSuccessOutcome(label) {
    return /success|accepted|reached|escaped|completed/i.test(String(label || ""));
  }

  function outcomeBadge(doc, x, y, label) {
    const isSuccess = isSuccessOutcome(label);
    const isPartial = /partial/i.test(label);
    const isDeadlock = /deadlock/i.test(label);
    const color = isSuccess ? C.teal : isPartial ? C.amber : isDeadlock ? [123, 77, 209] : C.red;
    const bgRgb = isSuccess ? [237, 249, 246] : isPartial ? [255, 246, 230] : isDeadlock ? [245, 240, 255] : [255, 240, 238];
    fc(doc, bgRgb);
    doc.roundedRect(x, y - 5, 36, 8, 2, 2, "F");
    dc(doc, color);
    doc.setLineWidth(0.3);
    doc.roundedRect(x, y - 5, 36, 8, 2, 2, "S");
    font(doc, 8, "bold", color);
    doc.text(label, x + 18, y, { align: "center" });
  }

  /* ── Small two-col key-value row ─────────────────────────────── */
  function kvRow(doc, y, label, value, highlight) {
    font(doc, 8, "normal", C.muted);
    doc.text(pdfSafe(label), M, y);
    font(doc, 8, "bold", highlight ? C.blue : C.navy);
    doc.text(pdfSafe(value || "—"), M + 48, y);
    return y + 6;
  }

  /* ── Draw a simple multi-series line chart ───────────────────── */
  function lineChart(doc, cx, cy, cw, ch, series, xLabels) {
    const PAD_L = 10, PAD_B = 10, PAD_T = 6, PAD_R = 4;
    const plotX = cx + PAD_L;
    const plotY = cy + PAD_T;
    const plotW = cw - PAD_L - PAD_R;
    const plotH = ch - PAD_T - PAD_B;

    /* background */
    fc(doc, [247, 250, 254]);
    dc(doc, C.line);
    doc.setLineWidth(0.2);
    doc.roundedRect(cx, cy, cw, ch, 3, 3, "FD");

    /* grid lines (4 horizontal) */
    for (let i = 0; i <= 4; i++) {
      const gy = plotY + (plotH / 4) * i;
      dc(doc, C.line);
      doc.setLineWidth(0.15);
      doc.line(plotX, gy, plotX + plotW, gy);
      /* y-axis label */
      font(doc, 5.5, "normal", C.muted);
      const pct = Math.round(100 - i * 25);
      doc.text(`${pct}%`, cx + 2, gy + 1.5);
    }

    /* x-axis ticks */
    if (xLabels && xLabels.length) {
      const step = Math.max(1, Math.floor(xLabels.length / 6));
      xLabels.forEach((lbl, i) => {
        if (i % step !== 0 && i !== xLabels.length - 1) return;
        const px = plotX + (plotW / (xLabels.length - 1 || 1)) * i;
        font(doc, 5.5, "normal", C.muted);
        doc.text(String(lbl), px, plotY + plotH + 7, { align: "center" });
      });
    }

    /* x-axis label */
    font(doc, 5.5, "normal", C.muted);
    doc.text("Step", plotX + plotW / 2, plotY + plotH + PAD_B - 1, { align: "center" });

    /* series lines */
    series.forEach(({ values, color, label }) => {
      if (!values || values.length < 2) return;
      const n = values.length;
      dc(doc, color);
      doc.setLineWidth(0.7);
      for (let i = 1; i < n; i++) {
        const x1 = plotX + (plotW / (n - 1)) * (i - 1);
        const x2 = plotX + (plotW / (n - 1)) * i;
        const y1 = plotY + plotH - Math.min(1, Math.max(0, values[i - 1])) * plotH;
        const y2 = plotY + plotH - Math.min(1, Math.max(0, values[i])) * plotH;
        doc.line(x1, y1, x2, y2);
      }
      /* dots at each point */
      doc.setLineWidth(0.3);
      fc(doc, color);
      values.forEach((v, i) => {
        const px = plotX + (plotW / (n - 1)) * i;
        const py = plotY + plotH - Math.min(1, Math.max(0, v)) * plotH;
        doc.circle(px, py, 0.8, "F");
      });
    });

    /* legend */
    let lx = plotX + plotW - 2;
    series.slice().reverse().forEach(({ color, label }) => {
      if (!label) return;
      font(doc, 6, "bold", color);
      const tw = doc.getTextWidth(label);
      doc.text(label, lx, cy + 5, { align: "right" });
      lx -= tw + 10;
    });
  }

  function safeArray(value) {
    return Array.isArray(value) ? value : [];
  }

  function safeNumber(value, fallback = 0) {
    const n = Number(value);
    return Number.isFinite(n) ? n : fallback;
  }

  function safeText(value, fallback = "Not recorded") {
    const text = String(value == null ? "" : value).trim();
    return text || fallback;
  }

  /**
   * Convert raw mode values (from either dashboard or interaction page) into
   * a clean human-readable label shown on the PDF cover and config pages.
   */
  function normalizeMode(mode) {
    const m = String(mode || "").toLowerCase().trim();
    if (m === "step")               return "Watch Mode";
    if (m === "auto")               return "Watch Mode";
    if (m === "watch_replay")       return "Watch Mode Replay";
    if (m === "interactive_replay") return "Live Interactive Replay";
    // Already a readable label (e.g. from interaction page payload)
    return mode || "Unknown mode";
  }

  function normalizeReportData(report) {
    const source = report && typeof report === "object" ? report : {};
    const warnings = [];

    const agents = safeArray(source.agents).map((agent, index) => ({
      id: safeText(agent?.id, `A${index + 1}`),
      name: safeText(agent?.id, `A${index + 1}`), // always the agent ID, never a separate name field
      role: safeText(agent?.role, "Agent"),
      personality: safeText(agent?.personality, ""),
      holds: safeText(agent?.holds, "No data available"),
      finalStress: agent?.finalStress == null ? null : safeNumber(agent.finalStress, 0),
    }));

    const tasks = safeArray(source.tasks).map((task, index) => ({
      label: safeText(task?.label, `Task ${index + 1}`),
      done: Boolean(task?.done),
    }));

    const metricsHistory = safeArray(source.metricsHistory).map((point, index) => ({
      tick: safeNumber(point?.tick, index + 1),
      progress: safeNumber(point?.progress, 0),
      trust: safeNumber(point?.trust, 0),
      stress: safeNumber(point?.stress, 0),
      conflict: safeNumber(point?.conflict, 0),
      cohesion: point?.cohesion == null ? null : safeNumber(point.cohesion, 0),
    }));

    const timeline = safeArray(source.timeline).map((step, index) => ({
      tick: safeNumber(step?.tick, index + 1),
      title: safeText(step?.title, "Interaction"),
      eventType: safeText(step?.eventType, ""),
      actorName: safeText(step?.actorName, ""),
      targetName: safeText(step?.targetName, ""),
      summary: safeText(step?.summary, "No summary recorded for this step."),
      message: safeText(step?.message, ""),
      actionDetails: safeArray(step?.actionDetails).map((entry) => safeText(entry, "")).filter(Boolean),
      effects: safeArray(step?.effects).map((entry) => typeof entry === "string" ? safeText(entry, "") : safeText(entry?.text, "")).filter(Boolean),
      whyTrigger: safeText(step?.whyTrigger, ""),
      whyReasoning: safeText(step?.whyReasoning, ""),
      whyImpact: safeText(step?.whyImpact, ""),
      hasEvent: Boolean(step?.hasEvent),
    }));

    const interventions = safeArray(source.interventions).map((iv, index) => ({
      tick: safeNumber(iv?.tick, index + 1),
      label: safeText(iv?.label || iv?.type, "Intervention"),
      type: safeText(iv?.type, ""),
      stressChange: iv?.stressChange == null ? null : safeNumber(iv.stressChange, 0),
      trustChange: iv?.trustChange == null ? null : safeNumber(iv.trustChange, 0),
      conflictChange: iv?.conflictChange == null ? null : safeNumber(iv.conflictChange, 0),
      verdict: safeText(iv?.verdict, ""),
    }));

    const normalized = {
      runId: safeText(source.runId, source.id || "unknown-run"),
      seed: safeText(source.seed, "Not recorded"),
      exportedAt: safeText(source.exportedAt, new Date().toLocaleString("en-GB")),
      scenario: {
        id: safeText(source.scenario?.id, "unknown-scenario"),
        label: safeText(source.scenario?.label || source.scenarioName, "Unknown scenario"),
        title: safeText(source.scenario?.title || source.scenario?.label || source.scenarioName, "Simulation run"),
      },
      team: {
        key: safeText(source.team?.key, ""),
        label: safeText(source.team?.label || source.teamStyle, "Unknown team"),
      },
      mode: normalizeMode(safeText(source.mode, "Unknown mode")),
      outcome: safeText(source.outcome, "Incomplete"),
      totalSteps: safeNumber(source.totalSteps, timeline.length || metricsHistory.length || 0),
      agents,
      tasks,
      finalMetrics: {
        progress: safeNumber(source.finalMetrics?.progress, 0),
        trust: safeNumber(source.finalMetrics?.trust, 0),
        stress: safeNumber(source.finalMetrics?.stress, 0),
        conflict: safeNumber(source.finalMetrics?.conflict ?? source.finalMetrics?.friction, 0),
        cohesion: source.finalMetrics?.cohesion == null ? null : safeNumber(source.finalMetrics.cohesion, 0),
      },
      metricsHistory,
      timeline,
      interventions,
      outcomeSummary: safeText(source.outcomeSummary, ""),
    };

    if (!source.runId && !source.id) warnings.push("Missing run ID");
    if (!agents.length) warnings.push("No agents recorded");
    if (!timeline.length) warnings.push("No step timeline recorded");
    if (!metricsHistory.length) warnings.push("No metric history recorded");
    if (!tasks.length) warnings.push("No task status recorded");
    normalized._warnings = warnings;
    return normalized;
  }

  function fallbackReport(doc, d, error) {
    pageHeader(doc, "Fallback Report", "1 of 1");
    let y = 24;
    y = eyebrow(doc, y, "Export fallback");
    y = sectionHead(doc, y, "Minimal Run Report");
    y = insightBox(
      doc,
      y,
      "The full PDF report could not be rendered, so SimuVerse generated this minimal fallback report instead.",
      CW
    );
    y += 3;
    y = kvRow(doc, y, "Run ID", d.runId, true);
    y = kvRow(doc, y, "Scenario", d.scenario?.label);
    y = kvRow(doc, y, "Team style", d.team?.label);
    y = kvRow(doc, y, "Mode", d.mode);
    y = kvRow(doc, y, "Outcome", d.outcome);
    y = kvRow(doc, y, "Total steps", d.totalSteps);
    y += 5;
    y = eyebrow(doc, y, "Technical note");
    y = textBlock(
      doc,
      M,
      y,
      CW,
      `The export pipeline encountered a rendering error: ${safeText(error?.message, "Unknown rendering error")}. Missing or invalid report fields were replaced with fallback values where possible.`,
      8.5,
      "normal",
      C.muted2,
      5.2
    );
    if (d._warnings?.length) {
      y += 2;
      y = textBlock(
        doc,
        M,
        y,
        CW,
        `Data warnings: ${d._warnings.join("; ")}.`,
        8,
        "normal",
        C.muted,
        4.8
      );
    }
    pageFooter(doc, d.runId, 1, 1);
  }

  /* ── Outcome interpretation text ─────────────────────────────── */
  function outcomeInterpretation(outcome, finalMetrics, teamLabel) {
    const prog    = finalMetrics.progress || 0;
    // Progress is stored as a 0–1 fraction; display as a whole percentage.
    const progPct = Math.round(prog <= 1 ? prog * 100 : prog);
    const trust   = finalMetrics.trust  || 0;
    const stress  = finalMetrics.stress || 0;
    const team    = String(teamLabel || "").toLowerCase();

    // Success outcomes — use outcome label rather than a raw progress number
    if (/success|accepted|reached|escaped|completed/i.test(outcome) && team.includes("tension")) {
      return `The Tension Team completed all required tasks despite starting with lower initial trust. Trust reached ${trust.toFixed(2)}, suggesting that initially guarded behaviour stabilised once the key information was shared.`;
    }
    if (/success|accepted|reached|escaped|completed/i.test(outcome) && trust > 0.6) {
      return `High trust (${trust.toFixed(2)}) and manageable stress enabled smooth information sharing. All required tasks were resolved without significant friction.`;
    }
    if (/success|accepted|reached|escaped|completed/i.test(outcome)) {
      return `The team resolved all required tasks (${progPct}% completion). Trust and stress levels indicate a successful run, though some pressure remained visible by the end.`;
    }
    if (/partial/i.test(outcome)) {
      return `The run ended at ${progPct}% completion. Some tasks were resolved but key blockers remained uncleared. Trust was ${trust.toFixed(2)} — cooperation was present but insufficient to finish.`;
    }
    if (/deadlock/i.test(outcome)) {
      return `A deadlock occurred: agents stopped progressing despite having unresolved tasks. Stress reached ${stress.toFixed(2)}, indicating blocked coordination. No further task completion was possible.`;
    }
    if (progPct >= 100) {
      return `All tasks were completed (100%) and the run finished successfully. Trust was ${trust.toFixed(2)} and stress was ${stress.toFixed(2)} at the end.`;
    }
    return `The run ended at ${progPct}% progress. Review the step timeline and intervention log for the cause of this outcome.`;
  }

  /* ── Safe PDF text normalisation ─────────────────────────────── */
  function pdfSafe(value) {
    return String(value == null ? "" : value)
      .replace(/\r\n/g, "\n")
      .replace(/[‐‑–—]/g, "-")
      .replace(/[“”]/g, '"')
      .replace(/[‘’]/g, "'")
      .replace(/→/g, "->")
      .replace(/✓/g, "[Complete]")
      .replace(/✗/g, "[Open]")
      .replace(/•/g, "-")
      .replace(/·/g, " | ")
      .replace(/…/g, "...")
      .replace(/\bthe the\b/gi, "the")
      .replace(/[\u0000-\u0008\u000B-\u001F\u007F-\u009F]/g, "")
      .trim();
  }

  /* ── Format a metric value for display ──────────────────────── */
  function fmtMetric(v, isPercent) {
    if (v == null || v === "") return "—";
    if (isPercent) {
      const n = Number(v);
      const pct = n <= 1 ? Math.round(n * 100) : Math.round(n);
      return `${pct}%`;
    }
    return Number(v).toFixed(2);
  }

  /* ── Wrap and print text block ───────────────────────────────── */
  function textBlock(doc, x, y, maxW, text, size, weight, color, lineH) {
    font(doc, size || 9, weight || "normal", color || C.muted2);
    const lines = doc.splitTextToSize(pdfSafe(text), maxW || CW);
    doc.text(lines, x, y);
    return y + lines.length * (lineH || (size ? size * 0.52 : 5));
  }

  /* ── Highlighted insight box ─────────────────────────────────── */
  function insightBox(doc, y, text, maxW) {
    const wrapped = doc.splitTextToSize(pdfSafe(text), (maxW || CW) - 12);
    const bh = wrapped.length * 5 + 10;
    fc(doc, C.bgBlue);
    dc(doc, C.blue);
    doc.setLineWidth(0.3);
    doc.roundedRect(M, y, maxW || CW, bh, 3, 3, "FD");
    /* left accent bar */
    fc(doc, C.blue);
    doc.rect(M, y, 2.5, bh, "F");
    font(doc, 8.5, "normal", C.navy);
    doc.text(wrapped, M + 8, y + 7);
    return y + bh + 5;
  }

  /* ══════════════════════════════════════════════════════════════
     PAGE BUILDERS
     ══════════════════════════════════════════════════════════════ */

  /* ── Page 1: Executive Summary / Cover ──────────────────────── */
  function page1Cover(doc, d, pg, total) {
    pageHeader(doc, "Executive Summary", `${pg} of ${total}`);

    /* Brand stripe */
    fc(doc, C.navy);
    doc.rect(M, 20, CW, 38, "F");
    /* subtle blue glow top-right */
    fc(doc, C.blue);
    doc.rect(W - M - 30, 20, 30, 38, "F");
    fc(doc, [12, 28, 52]);
    doc.rect(W - M - 30, 20, 30, 38, "F");

    font(doc, 22, "bold", C.white);
    doc.text("SimuVerse", M + 8, 37);
    font(doc, 10, "normal", [160, 185, 215]);
    doc.text("Run Report", M + 8, 44);

    /* Outcome badge on right */
    font(doc, 7, "bold", [180, 200, 225]);
    doc.text("OUTCOME", W - M - 28, 29);
    outcomeBadge(doc, W - M - 10, 41, d.outcome);

    let y = 66;

    /* ── Meta grid ── */
    const left = M, right = M + CW / 2 + 4;

    y = kvRow(doc, y, "Scenario", pdfSafe(d.scenario.label));
    y = kvRow(doc, y, "Team style", pdfSafe(d.team.label));
    y = kvRow(doc, y, "Experience mode", pdfSafe(d.mode));
    y = kvRow(doc, y, "Steps completed", d.totalSteps);
    y = kvRow(doc, y, "Date exported", d.exportedAt);
    y += 3;
    hRule(doc, y); y += 6;
    y = kvRow(doc, y, "Run ID", pdfSafe(d.runId), true);
    y = kvRow(doc, y, "Seed", pdfSafe(d.seed), true);
    y = kvRow(doc, y, "Replay available", "Yes — use Run ID to replay");
    y += 8;

    /* ── Metric chips row ── */
    const chipW = (CW - 9) / 4;
    metricChip(doc, M,                    y, chipW, "Progress",     fmtMetric(d.finalMetrics.progress, true),  C.blue,  "Final");
    metricChip(doc, M + chipW + 3,        y, chipW, "Team Trust",   fmtMetric(d.finalMetrics.trust),           C.teal,  "0–1 scale");
    metricChip(doc, M + (chipW + 3) * 2,  y, chipW, "Team Stress",  fmtMetric(d.finalMetrics.stress),          C.red,   "0–1 scale");
    metricChip(doc, M + (chipW + 3) * 3,  y, chipW, "Friction",     fmtMetric(d.finalMetrics.conflict),        C.amber, "0–1 scale");
    y += 28;

    /* ── Executive summary box ── */
    y = eyebrow(doc, y, "Summary");
    const summaryText = d.outcomeSummary || outcomeInterpretation(d.outcome, d.finalMetrics, d.team?.label);
    y = insightBox(doc, y, summaryText, CW);

    /* ── Reproducibility note ── */
    y += 2;
    y = eyebrow(doc, y, "Reproducibility");
    y = textBlock(doc, M, y, CW,
      `This report can be reproduced using Run ID ${d.runId} and seed ${d.seed}. ` +
      `Open SimuVerse, go to History, find this run, and press Replay.`,
      8.5, "normal", C.muted2, 5.2);

    pageFooter(doc, d.runId, pg, total);
  }

  /* ── Page 2: Run Configuration & Agents ─────────────────────── */
  function page2Config(doc, d, pg, total) {
    pageHeader(doc, "Run Configuration", `${pg} of ${total}`);
    let y = 24;

    y = eyebrow(doc, y, "Setup");
    y = sectionHead(doc, y, "Run Configuration & Agents");

    /* Config block */
    const leftW = CW * 0.55 - 6;
    const rightX = M + CW * 0.55;
    const rightW = CW * 0.45;

    /* Left: key-value config */
    let ly = y;
    font(doc, 7, "bold", C.muted);
    doc.text("SIMULATION SETUP", M, ly); ly += 6;

    const cfgRows = [
      ["Scenario",      d.scenario.label],
      ["Scenario ID",   d.scenario.id],
      ["Team style",    d.team.label],
      ["Experience",    d.mode],
      ["Total steps",   d.totalSteps],
      ["Outcome",       d.outcome],
      ["Run ID",        d.runId],
      ["Seed",          d.seed],
      ["Exported",      d.exportedAt],
    ];

    cfgRows.forEach(([lbl, val]) => {
      font(doc, 8, "normal", C.muted);
      doc.text(lbl, M, ly);
      font(doc, 8, "bold", C.navy);
      doc.text(String(val || "—"), M + 38, ly);
      ly += 6;
    });

    /* Right: initial blockers / tasks */
    let ry = y;
    font(doc, 7, "bold", C.muted);
    doc.text("TASK STATUS AT END", rightX, ry); ry += 6;

    (d.tasks || []).forEach((task) => {
      const done = task.done;
      fc(doc, done ? [237, 249, 246] : [255, 240, 238]);
      doc.roundedRect(rightX, ry - 4.5, rightW, 8, 2, 2, "F");
      font(doc, 7, "bold", done ? C.teal : C.red);
      doc.text(done ? "OK" : "OPEN", rightX + 3, ry);
      font(doc, 8, done ? "bold" : "normal", done ? C.navy : C.muted2);
      doc.text(pdfSafe(task.label || ""), rightX + 14, ry);
      ry += 10;
    });

    y = Math.max(ly, ry) + 8;
    hRule(doc, y); y += 8;

    /* Agents table */
    y = eyebrow(doc, y, "Agents");
    font(doc, 12, "bold", C.navy); doc.text("Agent Roster", M, y + 6); y += 12;

    if (d.agents && d.agents.length) {
      d.agents.forEach((a) => {
        if (y > H - 34) return;
        fc(doc, [248, 251, 255]);
        dc(doc, C.line);
        doc.setLineWidth(0.25);
        doc.roundedRect(M, y - 2, CW, 14, 3, 3, "FD");
        font(doc, 8.5, "bold", C.navy);
        // Always show the agent ID (A1–A4), never a human name field.
        doc.text(`${pdfSafe(a.id || "Agent")} — ${pdfSafe(a.role || "Agent")}`, M + 4, y + 3);
        font(doc, 7.5, "normal", C.muted2);
        const detailParts = [];
        if (a.personality) detailParts.push(`Trait: ${pdfSafe(a.personality)}`);
        detailParts.push(`Holds: ${pdfSafe(a.holds || "—")}`);
        detailParts.push(`Final stress: ${a.finalStress != null ? Number(a.finalStress).toFixed(2) : "—"}`);
        doc.text(detailParts.join("  |  "), M + 4, y + 8);
        y += 16;
      });
      y += 2;
    } else {
      y = textBlock(
        doc,
        M,
        y,
        CW,
        "Agent roster details were not present in the saved payload for this run.",
        8,
        "normal",
        C.muted2,
        4.8
      );
    }

    /* Reproducibility note */
    hRule(doc, y); y += 6;
    y = eyebrow(doc, y, "Reproducibility");
    y = textBlock(doc, M, y, CW,
      `To reproduce this exact run: use Run ID "${d.runId}" with seed "${d.seed}". ` +
      `The same initial configuration will produce an identical agent decision sequence.`,
      8.5, "normal", C.muted2, 5.2);

    pageFooter(doc, d.runId, pg, total);
  }

  /* ── Page 3: Final Metrics Summary ──────────────────────────── */
  function page3Metrics(doc, d, pg, total) {
    pageHeader(doc, "Final Metrics Summary", `${pg} of ${total}`);
    let y = 24;

    y = eyebrow(doc, y, "Results");
    y = sectionHead(doc, y, "Final Metrics Summary");

    /* Large metric chips in 2x2 grid */
    const chipW = (CW - 6) / 2;
    const chipH = 32;

    const chips = [
      { label: "Progress",   value: fmtMetric(d.finalMetrics.progress, true),  color: C.blue,  note: "% of tasks completed" },
      { label: "Team Trust", value: fmtMetric(d.finalMetrics.trust),           color: C.teal,  note: "0 = none · 1 = full" },
      { label: "Team Stress",value: fmtMetric(d.finalMetrics.stress),          color: C.red,   note: "0 = calm · 1 = max pressure" },
      { label: "Friction",   value: fmtMetric(d.finalMetrics.conflict),        color: C.amber, note: "0 = smooth · 1 = high conflict" },
    ];

    chips.forEach((chip, i) => {
      const col = i % 2, row = Math.floor(i / 2);
      const cx = M + col * (chipW + 6);
      const cy = y + row * (chipH + 6);

      fc(doc, chip.color === C.blue ? C.bgBlue : chip.color === C.teal ? [237, 249, 246] :
             chip.color === C.red ? [255, 240, 238] : [255, 246, 230]);
      doc.roundedRect(cx, cy, chipW, chipH, 4, 4, "F");
      dc(doc, chip.color);
      doc.setLineWidth(0.5);
      doc.roundedRect(cx, cy, chipW, chipH, 4, 4, "S");
      /* accent left bar */
      fc(doc, chip.color);
      doc.rect(cx, cy, 3, chipH, "F");
      font(doc, 7, "bold", C.muted);
      doc.text(chip.label.toUpperCase(), cx + 8, cy + 8);
      font(doc, 22, "bold", chip.color);
      doc.text(chip.value, cx + 8, cy + 22);
      font(doc, 6.5, "normal", C.muted);
      doc.text(chip.note, cx + 8, cy + 29);
    });

    y += 2 * (chipH + 6) + 8;

    /* Steps completed */
    fc(doc, C.bg);
    doc.roundedRect(M, y, CW, 12, 3, 3, "F");
    font(doc, 8, "bold", C.muted);
    doc.text("STEPS COMPLETED", M + 6, y + 5);
    font(doc, 10, "bold", C.navy);
    doc.text(String(d.totalSteps), M + 6, y + 11);
    font(doc, 8, "normal", C.muted);
    doc.text("total agent interaction steps recorded in this run", M + 22, y + 11);
    y += 18;

    hRule(doc, y); y += 8;

    /* Interpretation box */
    y = eyebrow(doc, y, "Interpretation");
    font(doc, 12, "bold", C.navy);
    doc.text("What these numbers mean", M, y + 6); y += 12;

    const interpretation = outcomeInterpretation(d.outcome, d.finalMetrics, d.team?.label);
    y = insightBox(doc, y, interpretation, CW);

    /* Metric direction guide */
    y += 2;
    font(doc, 7.5, "bold", C.muted);
    doc.text("METRIC DIRECTION GUIDE", M, y); y += 6;

    const guide = [
      { c: C.blue,  text: "Progress - higher is better. 100% = all tasks resolved." },
      { c: C.teal,  text: "Trust - higher means stronger cooperation between agents." },
      { c: C.red,   text: "Stress - lower is better. High stress slows task completion." },
      { c: C.amber, text: "Friction - lower means smoother agent interactions." },
    ];

    guide.forEach(({ c, text }) => {
      fc(doc, c);
      doc.circle(M + 2, y - 1, 1.5, "F");
      font(doc, 8, "normal", C.muted2);
      doc.text(pdfSafe(text), M + 7, y);
      y += 6;
    });

    pageFooter(doc, d.runId, pg, total);
  }

  /* ── Page 4: Metrics Over Time (chart) ──────────────────────── */
  function page4Chart(doc, d, pg, total) {
    pageHeader(doc, "Metrics Over Time", `${pg} of ${total}`);
    let y = 24;

    y = eyebrow(doc, y, "Trend analysis");
    y = sectionHead(doc, y, "Metrics Over Time");

    const hist = d.metricsHistory;

    if (!hist || hist.length < 2) {
      textBlock(doc, M, y, CW, "Insufficient data to draw the chart for this run.", 9, "normal", C.muted);
      pageFooter(doc, d.runId, pg, total);
      return;
    }

    const ticks = hist.map((h) => h.tick);
    const progress = hist.map((h) => Number(h.progress || 0));
    const trust    = hist.map((h) => Number(h.trust    || 0));
    const stress   = hist.map((h) => Number(h.stress   || 0));

    /* Draw the chart */
    lineChart(
      doc, M, y, CW, 78,
      [
        { values: progress, color: C.blue,  label: "Progress" },
        { values: trust,    color: C.teal,  label: "Trust" },
        { values: stress,   color: C.red,   label: "Stress" },
      ],
      ticks
    );
    y += 86;

    y = textBlock(
      doc,
      M,
      y,
      CW,
      "All recorded steps are plotted in sequence so the metric trend can be read continuously from start to finish.",
      7.5,
      "normal",
      C.muted,
      4.6
    );
    y += 2;

    /* Chart insight */
    hRule(doc, y); y += 8;
    y = eyebrow(doc, y, "Insight");
    font(doc, 12, "bold", C.navy); doc.text("Chart interpretation", M, y + 6); y += 12;

    /* auto-generate insight from data */
    const avgStress  = stress.reduce((a, b) => a + b, 0) / stress.length;
    const trustDelta = trust[trust.length - 1] - trust[0];
    const progEnd    = progress[progress.length - 1]; // 0–1 fraction

    // Use final task completion from finalMetrics for the progress figure,
    // since per-tick progress may not be available for all run types.
    const authorativeProg = d.finalMetrics.progress || 0;
    const progPct = Math.round(authorativeProg <= 1 ? authorativeProg * 100 : authorativeProg);

    let insight = "";
    if (progPct >= 100 || progEnd >= 0.99) {
      insight = "Progress reached 100%, confirming all tasks were resolved. ";
    } else if (progPct > 0) {
      insight = `${progPct}% of tasks were completed by the end of the run. `;
    } else if (progEnd > 0) {
      insight = `Progress reached ${Math.round(progEnd * 100)}% by the end of the run. `;
    } else {
      // No per-tick progress data (Interaction mode without task snapshots); derive from outcome
      if (/success|accepted|reached|escaped|completed/i.test(d.outcome)) {
        insight = "All required tasks were completed successfully. ";
      } else {
        insight = "Task completion data was not recorded on a per-step basis for this run. ";
      }
    }
    if (trustDelta > 0.05) {
      insight += `Trust increased by ${trustDelta.toFixed(2)} over the run, indicating improving agent cooperation. `;
    } else if (trustDelta < -0.05) {
      insight += `Trust declined by ${Math.abs(trustDelta).toFixed(2)}, suggesting rising tension between agents. `;
    } else {
      insight += "Trust remained relatively stable throughout the run. ";
    }
    if (avgStress < 0.2) {
      insight += "Average stress was low, indicating a calm and coordinated team.";
    } else if (avgStress > 0.5) {
      insight += "Average stress was high, indicating pressure and potential coordination difficulty.";
    } else {
      insight += "Stress was moderate — the team experienced some pressure but maintained progress.";
    }

    y = insightBox(doc, y, insight, CW);

    /* Cohesion note if available */
    if (d.metricsHistory[0]?.cohesion != null) {
      y += 2;
      const cohStart = d.metricsHistory[0].cohesion;
      const cohEnd   = d.metricsHistory[d.metricsHistory.length - 1].cohesion;
      y = textBlock(doc, M, y, CW,
        `Cohesion moved from ${cohStart.toFixed(2)} to ${cohEnd.toFixed(2)} across the run.`,
        8.5, "normal", C.muted2, 5.5);
    }

    pageFooter(doc, d.runId, pg, total);
  }

  /* ── Page 5: Step Timeline ───────────────────────────────────── */
  function page5Timeline(doc, d, pg, total) {
    pageHeader(doc, "Step Timeline", `${pg} of ${total}`);
    let y = 24;

    y = eyebrow(doc, y, "Chronological record");
    y = sectionHead(doc, y, "Key Step Timeline");
    y = textBlock(
      doc,
      M,
      y,
      CW,
      "Showing each recorded simulation step in order, including steps with no agent message. Each step is labelled with a human-readable event title first, then the supporting interaction details.",
      7.8,
      "normal",
      C.muted,
      4.6
    );

    if (!d.timeline || !d.timeline.length) {
      y = textBlock(doc, M, y, CW, "No step timeline was recorded for this run.", 8.5, "normal", C.muted2, 5.2);
      pageFooter(doc, d.runId, pg, total);
      return;
    }

    (d.timeline || []).forEach((ev) => {
      const rawSummary = ev.summary || ev.message || (ev.hasEvent ? "Interaction recorded." : "");
      const summaryText = pdfSafe(rawSummary);
      const hasEffects = Array.isArray(ev.effects) && ev.effects.length;
      const hasActions = Array.isArray(ev.actionDetails) && ev.actionDetails.length;

      const wrappedSummary = summaryText
        ? doc.splitTextToSize(summaryText, CW - 24)
        : [];
      const wrappedActions = hasActions
        ? doc.splitTextToSize(pdfSafe(ev.actionDetails.join("  ·  ")), CW - 24)
        : [];
      const wrappedEffects = hasEffects
        ? doc.splitTextToSize(pdfSafe("Effects: " + ev.effects.join("; ")), CW - 24)
        : [];

      const contentLines = wrappedSummary.length + wrappedActions.length + wrappedEffects.length;
      const blockHeight = Math.max(16, 10 + contentLines * 3.8);
      if (y + blockHeight > H - 22) return;

      /* Card background */
      fc(doc, [248, 251, 255]);
      dc(doc, C.line);
      doc.setLineWidth(0.25);
      doc.roundedRect(M, y, CW, blockHeight, 3, 3, "FD");

      /* Step number circle */
      fc(doc, C.blue);
      doc.circle(M + 7, y + 7, 3.5, "F");
      font(doc, 7, "bold", C.white);
      doc.text(String(ev.tick || ""), M + 7, y + 8.4, { align: "center" });

      /* Title — event type label (human-readable, not raw snake_case) */
      const titleText = pdfSafe(ev.title || ev.eventType || "Interaction");
      font(doc, 8.2, "bold", C.navy);
      doc.text(doc.splitTextToSize(titleText, CW - 26), M + 15, y + 5.5);

      /* Actor line — show names if known, skip "—" filler */
      let actorLine = "";
      if (ev.actorName && ev.targetName) {
        actorLine = `${pdfSafe(ev.actorName)} \u2192 ${pdfSafe(ev.targetName)}`;
      } else if (ev.actorName) {
        actorLine = pdfSafe(ev.actorName);
      }
      if (actorLine) {
        font(doc, 7, "normal", C.muted);
        doc.text(actorLine, M + 15, y + 9.8);
      }

      let lineY = actorLine ? y + 13.5 : y + 10.5;

      /* Summary message */
      if (wrappedSummary.length) {
        font(doc, 7.4, "normal", C.muted2);
        doc.text(wrappedSummary, M + 15, lineY);
        lineY += wrappedSummary.length * 3.8;
      }

      /* Action details */
      if (wrappedActions.length) {
        font(doc, 7, "normal", C.muted);
        doc.text(wrappedActions, M + 15, lineY);
        lineY += wrappedActions.length * 3.8;
      }

      /* Effects */
      if (wrappedEffects.length) {
        font(doc, 7, "normal", C.muted);
        doc.text(wrappedEffects, M + 15, lineY);
      }

      y += blockHeight + 2.5;
    });

    pageFooter(doc, d.runId, pg, total);
  }

  /* ── Page 6: Intervention Impact ────────────────────────────── */
  function page6Interventions(doc, d, pg, total) {
    pageHeader(doc, "Intervention Impact", `${pg} of ${total}`);
    let y = 24;

    y = eyebrow(doc, y, "User interventions");
    y = sectionHead(doc, y, "Intervention Impact");

    if (!d.interventions || !d.interventions.length) {
      y = insightBox(
        doc,
        y,
        "No interventions applied. This run was completed in Watch Mode, so all progress came from autonomous agent interactions.",
        CW
      );
      y = textBlock(doc, M, y, CW,
        "Use Live Interactive mode to compare how interventions change stress, trust, cohesion, and friction across otherwise similar runs.",
        9, "normal", C.muted);
      pageFooter(doc, d.runId, pg, total);
      return;
    }

    font(doc, 8.5, "normal", C.muted2);
    doc.text(
      `${d.interventions.length} intervention${d.interventions.length !== 1 ? "s" : ""} were applied during this run.`,
      M, y
    );
    y += 8;

    const rows = d.interventions.map((iv) => {
      const sc = iv.stressChange  != null ? (iv.stressChange  > 0 ? `+${iv.stressChange.toFixed(2)}`  : iv.stressChange.toFixed(2))  : "—";
      const tc = iv.trustChange   != null ? (iv.trustChange   > 0 ? `+${iv.trustChange.toFixed(2)}`   : iv.trustChange.toFixed(2))   : "—";
      const cc = iv.conflictChange!= null ? (iv.conflictChange> 0 ? `+${iv.conflictChange.toFixed(2)}` : iv.conflictChange.toFixed(2)): "—";
      const verdict = iv.verdict || (
        (iv.stressChange || 0) < 0 || (iv.trustChange || 0) > 0 ? "Positive" :
        (iv.stressChange || 0) > 0 || (iv.trustChange || 0) < 0 ? "Negative" : "Neutral"
      );
      return [
        String(iv.tick || "—"),
        pdfSafe(iv.label || iv.type || "—"),
        sc, tc, cc,
        pdfSafe(verdict),
      ];
    });

    doc.autoTable({
      startY: y,
      margin: { left: M, right: M },
      theme: "plain",
      headStyles: {
        fillColor: C.navy,
        textColor: C.white,
        fontSize: 7.5,
        fontStyle: "bold",
        cellPadding: { top: 3, bottom: 3, left: 3, right: 3 },
      },
      bodyStyles: {
        fontSize: 8,
        textColor: C.navy,
        cellPadding: { top: 3.5, bottom: 3.5, left: 3, right: 3 },
      },
      alternateRowStyles: { fillColor: C.bg },
      columnStyles: {
        0: { cellWidth: 12, halign: "center", fontStyle: "bold" },
        1: { cellWidth: 68 },
        2: { cellWidth: 18, halign: "center" },
        3: { cellWidth: 18, halign: "center" },
        4: { cellWidth: 18, halign: "center" },
        5: { cellWidth: "auto", halign: "center" },
      },
      head: [["Step", "Intervention", "Stress Δ", "Trust Δ", "Friction Δ", "Verdict"]],
      body: rows,
      didParseCell: (data) => {
        if (data.section === "body" && data.column.index === 5) {
          const val = String(data.cell.raw || "").toLowerCase();
          if (val === "positive" || val === "effective") data.cell.styles.textColor = C.teal;
          else if (val === "negative" || val === "backfired") data.cell.styles.textColor = C.red;
          else data.cell.styles.textColor = C.muted;
          data.cell.styles.fontStyle = "bold";
        }
        if (data.section === "body" && data.column.index >= 2 && data.column.index <= 4) {
          const val = String(data.cell.raw || "");
          if (val.startsWith("+")) data.cell.styles.textColor = data.column.index === 2 ? C.red : C.teal;
          else if (val.startsWith("-")) data.cell.styles.textColor = data.column.index === 2 ? C.teal : C.red;
          data.cell.styles.fontStyle = "bold";
        }
      },
    });

    y = doc.lastAutoTable.finalY + 10;
    hRule(doc, y); y += 6;

    y = textBlock(doc, M, y, CW,
      "Metric direction: lower Stress/Friction is better (negative delta = improvement). " +
      "Higher Trust is better (positive delta = improvement). " +
      "A positive verdict means the intervention moved at least one metric in a beneficial direction.",
      8, "normal", C.muted, 5.2);

    pageFooter(doc, d.runId, pg, total);
  }

  /* ── Page 7: Outcome Explanation ────────────────────────────── */
  function page7Outcome(doc, d, pg, total) {
    pageHeader(doc, "Outcome Explanation", `${pg} of ${total}`);
    let y = 24;

    y = eyebrow(doc, y, "Why the run ended this way");
    y = sectionHead(doc, y, "Outcome Explanation");

    /* Outcome banner */
    const isSuccess = isSuccessOutcome(d.outcome);
    const bannerColor = isSuccess ? C.teal : /partial/i.test(d.outcome) ? C.amber : C.red;
    fc(doc, isSuccess ? [237, 249, 246] : /partial/i.test(d.outcome) ? [255, 246, 230] : [255, 240, 238]);
    doc.roundedRect(M, y, CW, 14, 4, 4, "F");
    fc(doc, bannerColor);
    doc.rect(M, y, 3.5, 14, "F");
    font(doc, 7.5, "bold", bannerColor);
    doc.text("FINAL OUTCOME", M + 8, y + 5.5);
    font(doc, 11, "bold", C.navy);
    doc.text(pdfSafe(d.outcome), M + 8, y + 12);
    y += 20;

    /* Why sections from final step */
    const finalStep = d.timeline?.[d.timeline.length - 1];

    const sections = [
      {
        title: "What happened",
        text: d.outcomeSummary || outcomeInterpretation(d.outcome, d.finalMetrics, d.team?.label),
      },
      finalStep?.whyTrigger ? {
        title: "Trigger",
        text: finalStep.whyTrigger,
      } : null,
      finalStep?.whyReasoning ? {
        title: "Reasoning",
        text: finalStep.whyReasoning,
      } : null,
      finalStep?.whyImpact ? {
        title: "Final impact",
        text: pdfSafe(finalStep.whyImpact),
      } : null,
    ].filter(Boolean);

    sections.forEach(({ title, text }) => {
      font(doc, 9, "bold", C.navy);
      doc.text(title, M, y); y += 6;
      y = textBlock(doc, M, y, CW, text, 8.5, "normal", C.muted2, 5.2);
      y += 4;
    });

    y += 4;
    hRule(doc, y); y += 8;

    /* Task completion summary */
    y = eyebrow(doc, y, "Task completion");
    font(doc, 12, "bold", C.navy); doc.text("Final Task Status", M, y + 6); y += 12;

    const doneTasks   = (d.tasks || []).filter((t) => t.done);
    const openTasks   = (d.tasks || []).filter((t) => !t.done);
    const pct = d.tasks?.length ? Math.round((doneTasks.length / d.tasks.length) * 100) : 0;

    font(doc, 8.5, "normal", C.muted2);
    doc.text(
      `${doneTasks.length} of ${d.tasks?.length || 0} tasks completed (${pct}%).`,
      M, y
    );
    y += 8;

    if (!d.tasks?.length) {
      y = textBlock(doc, M, y, CW, "No task-status data was recorded for this run.", 8.5, "normal", C.muted2, 5.2);
      pageFooter(doc, d.runId, pg, total);
      return;
    }

    if (doneTasks.length) {
      font(doc, 7.5, "bold", C.teal);
      doc.text("Completed:", M, y); y += 5;
      doneTasks.forEach((t) => {
        font(doc, 8, "normal", C.muted2);
        doc.text(`[Complete] ${pdfSafe(t.label)}`, M + 4, y); y += 5.5;
      });
    }
    if (openTasks.length) {
      y += 2;
      font(doc, 7.5, "bold", C.red);
      doc.text("Not completed:", M, y); y += 5;
      openTasks.forEach((t) => {
        font(doc, 8, "normal", C.muted2);
        doc.text(`[Open] ${pdfSafe(t.label)}`, M + 4, y); y += 5.5;
      });
    }

    pageFooter(doc, d.runId, pg, total);
  }

  /* ── Page 8 (optional): Full event log appendix ─────────────── */
  function page8Appendix(doc, d, pg, total) {
    pageHeader(doc, "Appendix: Full Event Log", `${pg} of ${total}`);
    let y = 24;

    y = eyebrow(doc, y, "Appendix");
    y = sectionHead(doc, y, "Full Event Log");

    const totalSteps = d.totalSteps || d.timeline?.length || 0;
    const recordedSteps = (d.timeline || []).filter((ev) => ev.hasEvent).length;
    font(doc, 8, "normal", C.muted2);
    doc.text(
      `${totalSteps} simulation steps, ${recordedSteps} recorded interaction step${recordedSteps === 1 ? "" : "s"}.`,
      M, y
    );
    y += 8;

    if (!d.timeline || !d.timeline.length) {
      y = textBlock(doc, M, y, CW, "No event log was recorded for this run.", 8.5, "normal", C.muted2, 5.2);
      pageFooter(doc, d.runId, pg, total);
      return;
    }

    const rows = (d.timeline || []).map((ev) => {
      const message = ev.hasEvent
        ? pdfSafe(ev.message || ev.summary || "Interaction recorded.")
        : "No agent message was recorded for this step.";
      const actorPart = ev.actorName && ev.targetName
        ? `${pdfSafe(ev.actorName)} -> ${pdfSafe(ev.targetName)}`
        : ev.actorName ? pdfSafe(ev.actorName) : "—";
      const typePart = ev.title || ev.eventType
        ? pdfSafe(ev.title || ev.eventType)
        : "Interaction";
      return [
        String(ev.tick || "—"),
        typePart,
        actorPart,
        message,
      ];
    });

    doc.autoTable({
      startY: y,
      margin: { left: M, right: M, bottom: 18 },
      theme: "grid",
      headStyles: {
        fillColor: C.navy,
        textColor: C.white,
        fontSize: 7.2,
        fontStyle: "bold",
        cellPadding: { top: 2.8, bottom: 2.8, left: 2.5, right: 2.5 },
        lineColor: C.line,
        lineWidth: 0.1,
      },
      bodyStyles: {
        fontSize: 7.2,
        textColor: C.navy,
        cellPadding: { top: 2.6, bottom: 2.6, left: 2.5, right: 2.5 },
        valign: "top",
        overflow: "linebreak",
        lineColor: C.line,
        lineWidth: 0.1,
      },
      alternateRowStyles: { fillColor: [248, 251, 255] },
      columnStyles: {
        0: { cellWidth: 14, halign: "center", fontStyle: "bold" },
        1: { cellWidth: 42 },
        2: { cellWidth: 38 },
        3: { cellWidth: "auto" },
      },
      head: [["Step", "Event", "Participants", "Message"]],
      body: rows,
      didDrawPage: (data) => {
        if (data.pageNumber > 1) {
          const pageNumber = pg + data.pageNumber - 1;
          pageHeader(doc, "Appendix: Full Event Log", `Page ${pageNumber}`);
        }
        const currentPage = doc.internal.getNumberOfPages();
        pageFooter(doc, d.runId, currentPage, null);
      },
    });
  }

  /* ══════════════════════════════════════════════════════════════
     MAIN ENTRY POINT
     ══════════════════════════════════════════════════════════════ */

  function generate(inputData) {
    if (!window.jspdf || !window.jspdf.jsPDF) {
      console.error("[SimuVersePDF] jsPDF not loaded. Cannot generate PDF.");
      return { ok: false, mode: "error", reason: "library-missing" };
    }

    const { jsPDF } = window.jspdf;
    const d = normalizeReportData(inputData);
    const slug = String(d.scenario?.id || "run").replace(/[^a-z0-9]/gi, "-");
    const safeRunId = String(d.runId || "run");
    const ts = new Date().toISOString().slice(0, 10);
    const filename = `simuverse-report-${slug}-${safeRunId.slice(0, 8)}-${ts}.pdf`;

    try {
      const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

      const hasLongLog = d.timeline && d.timeline.length > 12;
      const total = 7 + (hasLongLog ? 1 : 0);
      let pg = 1;

      page1Cover(doc, d, pg++, total);
      doc.addPage();
      page2Config(doc, d, pg++, total);
      doc.addPage();
      page3Metrics(doc, d, pg++, total);
      doc.addPage();
      page4Chart(doc, d, pg++, total);
      doc.addPage();
      page5Timeline(doc, d, pg++, total);
      doc.addPage();
      page6Interventions(doc, d, pg++, total);
      doc.addPage();
      page7Outcome(doc, d, pg++, total);

      if (hasLongLog) {
        doc.addPage();
        page8Appendix(doc, d, pg++, total);
      }

      doc.save(filename);
      return { ok: true, mode: "full", warnings: d._warnings || [] };
    } catch (error) {
      console.error("[SimuVersePDF] Full PDF export failed.", error);
      const fallbackDoc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
      fallbackReport(fallbackDoc, d, error);
      fallbackDoc.save(filename);
      return { ok: true, mode: "fallback", warnings: d._warnings || [], error: error?.message || "Full render failed" };
    }
  }

  global.SimuVersePDF = { generate };

})(window);
